//! `lume` command-line tool.
//!
//!   lume build <file.lume> [-o <binary>]   compile to a native binary
//!   lume run   <file.lume> [-- args...]    compile and run
//!   lume emit  <file.lume>                 print the generated Rust
//!   lume check <file.lume>                 parse and check, emit nothing

mod ast;
mod codegen;
mod error;
mod lexer;
mod parser;

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{self, Command, Stdio};
use std::time::Instant;

fn usage() -> ! {
    eprintln!(
        "lume {}\n\nusage:\n  lume build <file.lume> [-o <binary>]\n  lume run   <file.lume> [-- <args>...]\n  lume emit  <file.lume>\n  lume check <file.lume>",
        env!("CARGO_PKG_VERSION")
    );
    process::exit(2);
}

fn compile_to_rust(path: &Path) -> Result<(String, String), String> {
    let src = fs::read_to_string(path)
        .map_err(|e| format!("error: cannot read `{}`: {}", path.display(), e))?;
    let file = path.display().to_string();
    let stage = || -> error::Result<String> {
        let toks = lexer::lex(&src)?;
        let program = parser::parse_program(toks)?;
        codegen::generate(&program)
    };
    match stage() {
        Ok(rust) => Ok((src, rust)),
        Err(e) => Err(e.render(&file, &src)),
    }
}

fn build(path: &Path, out: Option<PathBuf>, quiet: bool) -> Result<PathBuf, String> {
    let t0 = Instant::now();
    let (_src, rust) = compile_to_rust(path)?;
    let stem = path.file_stem().map(|s| s.to_string_lossy().to_string()).unwrap_or("out".into());
    let dir = path.parent().map(|p| p.to_path_buf()).unwrap_or_else(|| PathBuf::from("."));
    let build_dir = dir.join(".lume");
    fs::create_dir_all(&build_dir).map_err(|e| format!("error: cannot create `{}`: {}", build_dir.display(), e))?;
    let rs_path = build_dir.join(format!("{}.rs", stem));
    let header = format!("// Generated by lume from {} — edits here are overwritten.\n", path.display());
    fs::write(&rs_path, format!("{}{}", header, rust))
        .map_err(|e| format!("error: cannot write `{}`: {}", rs_path.display(), e))?;
    let bin = out.unwrap_or_else(|| build_dir.join(&stem));

    let status = Command::new("rustc")
        .args(["--edition", "2021", "-O", "-C", "debuginfo=0"])
        .arg("-o")
        .arg(&bin)
        .arg(&rs_path)
        .stdout(Stdio::inherit())
        .stderr(Stdio::piped())
        .output()
        .map_err(|e| format!("error: cannot run rustc: {}\n  help: install Rust from https://rustup.rs", e))?;
    if !status.status.success() {
        let err = String::from_utf8_lossy(&status.stderr);
        return Err(format!(
            "error: the generated Rust did not compile. This is a gap in the Lume compiler, not necessarily in your program.\n  generated file: {}\n\nrustc said:\n{}",
            rs_path.display(),
            err
        ));
    }
    if !quiet {
        eprintln!("compiled {} -> {} in {:.2}s", path.display(), bin.display(), t0.elapsed().as_secs_f64());
    }
    Ok(bin)
}

fn main() {
    let args: Vec<String> = env::args().skip(1).collect();
    if args.is_empty() {
        usage();
    }
    let cmd = args[0].as_str();
    let file = match args.get(1) {
        Some(f) if !f.starts_with('-') => PathBuf::from(f),
        _ => usage(),
    };
    if file.extension().map(|e| e != "lume").unwrap_or(true) {
        eprintln!("error: `{}` is not a .lume file", file.display());
        process::exit(2);
    }

    match cmd {
        "emit" => match compile_to_rust(&file) {
            Ok((_, rust)) => print!("{}", rust),
            Err(e) => {
                eprint!("{}", e);
                process::exit(1);
            }
        },
        "check" => match compile_to_rust(&file) {
            Ok(_) => eprintln!("ok: {}", file.display()),
            Err(e) => {
                eprint!("{}", e);
                process::exit(1);
            }
        },
        "build" => {
            let mut out = None;
            let mut i = 2;
            while i < args.len() {
                if args[i] == "-o" {
                    out = args.get(i + 1).map(PathBuf::from);
                    i += 2;
                } else {
                    usage();
                }
            }
            if let Err(e) = build(&file, out, false) {
                eprint!("{}", e);
                process::exit(1);
            }
        }
        "run" => {
            let prog_args: Vec<&String> = {
                let rest = &args[2..];
                match rest.iter().position(|a| a == "--") {
                    Some(p) => rest[p + 1..].iter().collect(),
                    None => rest.iter().collect(),
                }
            };
            let bin = match build(&file, None, true) {
                Ok(b) => b,
                Err(e) => {
                    eprint!("{}", e);
                    process::exit(1);
                }
            };
            let status = Command::new(&bin)
                .args(prog_args)
                .status()
                .unwrap_or_else(|e| {
                    eprintln!("error: cannot run `{}`: {}", bin.display(), e);
                    process::exit(1);
                });
            process::exit(status.code().unwrap_or(1));
        }
        _ => usage(),
    }
}
