//! `lume` command-line tool.
//!
//!   lume build <file.lume> [-o <binary>]   compile to a native binary
//!   lume run   <file.lume> [-- args...]    compile and run
//!   lume emit  <file.lume>                 print the generated Rust
//!   lume check <file.lume>                 parse and check, emit nothing

mod ast;
mod codegen;
mod error;
mod lexer;
mod parser;

use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::process::{self, Command, Stdio};
use std::time::Instant;

fn usage() -> ! {
    eprintln!(
        "lume {}\n\nusage:\n  lume build <file.lume> [-o <binary>]\n  lume run   <file.lume> [-- <args>...]\n  lume emit  <file.lume>\n  lume check <file.lume>",
        env!("CARGO_PKG_VERSION")
    );
    process::exit(2);
}

struct Compiled {
    rust: String,
    deps: Vec<(String, String)>,
    has_rust_blocks: bool,
}

fn rustc_failed_banner(has_rust_blocks: bool, file: &Path, tool: &str, err: &str) -> String {
    let why = if has_rust_blocks {
        "This program has `rust:` blocks; if the message below points inside one, the problem is in that Rust code. Otherwise it is a gap in the Lume compiler."
    } else {
        "This is a gap in the Lume compiler, not necessarily in your program."
    };
    format!("error: the generated Rust did not compile. {}\n  generated file: {}\n\n{} said:\n{}", why, file.display(), tool, err)
}

fn compile_to_rust(path: &Path) -> Result<Compiled, String> {
    let src = fs::read_to_string(path)
        .map_err(|e| format!("error: cannot read `{}`: {}", path.display(), e))?;
    let file = path.display().to_string();
    let stage = || -> error::Result<codegen::Output> {
        let toks = lexer::lex(&src)?;
        let program = parser::parse_program(toks)?;
        codegen::generate(&program)
    };
    match stage() {
        Ok(out) => {
            for w in out.warnings {
                eprint!("{}", w.render(&file, &src).replacen("error:", "warning:", 1));
            }
            Ok(Compiled { rust: out.rust, deps: out.deps, has_rust_blocks: out.has_rust_blocks })
        }
        Err(e) => Err(e.render(&file, &src)),
    }
}

/// Builds through cargo when the program imports Rust crates.
fn build_with_cargo(stem: &str, build_dir: &Path, rust: &str, deps: &[(String, String)], bin: &Path, has_rust_blocks: bool) -> Result<(), String> {
    let proj = build_dir.join(format!("cargo-{}", stem));
    let src_dir = proj.join("src");
    fs::create_dir_all(&src_dir).map_err(|e| format!("error: cannot create `{}`: {}", src_dir.display(), e))?;
    let pkg = stem.replace(|c: char| !c.is_alphanumeric() && c != '_', "_");
    let mut toml = format!("[package]\nname = \"{}\"\nversion = \"0.0.0\"\nedition = \"2021\"\n\n[dependencies]\n", pkg);
    for (k, v) in deps {
        toml.push_str(&format!("{} = \"{}\"\n", k, v));
    }
    toml.push_str("\n[profile.release]\nopt-level = 3\ndebug = false\n");
    fs::write(proj.join("Cargo.toml"), toml).map_err(|e| format!("error: cannot write Cargo.toml: {}", e))?;
    fs::write(src_dir.join("main.rs"), rust).map_err(|e| format!("error: cannot write main.rs: {}", e))?;
    let out = Command::new("cargo")
        .args(["build", "--release", "-q"])
        .current_dir(&proj)
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .output()
        .map_err(|e| format!("error: cannot run cargo: {}\n  help: install Rust from https://rustup.rs", e))?;
    if !out.status.success() {
        let err = String::from_utf8_lossy(&out.stderr);
        return Err(rustc_failed_banner(has_rust_blocks, &src_dir.join("main.rs"), "cargo", &err));
    }
    let built = proj.join("target").join("release").join(&pkg);
    fs::copy(&built, bin).map_err(|e| format!("error: cannot copy `{}` to `{}`: {}", built.display(), bin.display(), e))?;
    Ok(())
}

fn build(path: &Path, out: Option<PathBuf>, quiet: bool) -> Result<PathBuf, String> {
    let t0 = Instant::now();
    let compiled = compile_to_rust(path)?;
    let rust = compiled.rust;
    let stem = path.file_stem().map(|s| s.to_string_lossy().to_string()).unwrap_or("out".into());
    let dir = path.parent().map(|p| p.to_path_buf()).unwrap_or_else(|| PathBuf::from("."));
    let build_dir = dir.join(".lume");
    fs::create_dir_all(&build_dir).map_err(|e| format!("error: cannot create `{}`: {}", build_dir.display(), e))?;
    let rs_path = build_dir.join(format!("{}.rs", stem));
    let header = format!("// Generated by lume from {} — edits here are overwritten.\n", path.display());
    let rust = format!("{}{}", header, rust);
    fs::write(&rs_path, &rust).map_err(|e| format!("error: cannot write `{}`: {}", rs_path.display(), e))?;
    let bin = out.unwrap_or_else(|| build_dir.join(&stem));
    if !compiled.deps.is_empty() {
        build_with_cargo(&stem, &build_dir, &rust, &compiled.deps, &bin, compiled.has_rust_blocks)?;
        if !quiet {
            eprintln!("compiled {} -> {} in {:.2}s (cargo, {} crate{})", path.display(), bin.display(), t0.elapsed().as_secs_f64(), compiled.deps.len(), if compiled.deps.len() == 1 { "" } else { "s" });
        }
        return Ok(bin);
    }

    let status = Command::new("rustc")
        .args(["--edition", "2021", "-O", "-C", "debuginfo=0"])
        .arg("-o")
        .arg(&bin)
        .arg(&rs_path)
        .stdout(Stdio::inherit())
        .stderr(Stdio::piped())
        .output()
        .map_err(|e| format!("error: cannot run rustc: {}\n  help: install Rust from https://rustup.rs", e))?;
    if !status.status.success() {
        let err = String::from_utf8_lossy(&status.stderr);
        return Err(rustc_failed_banner(compiled.has_rust_blocks, &rs_path, "rustc", &err));
    }
    if !quiet {
        eprintln!("compiled {} -> {} in {:.2}s", path.display(), bin.display(), t0.elapsed().as_secs_f64());
    }
    Ok(bin)
}

fn main() {
    let args: Vec<String> = env::args().skip(1).collect();
    if args.is_empty() {
        usage();
    }
    let cmd = args[0].as_str();
    let file = match args.get(1) {
        Some(f) if !f.starts_with('-') => PathBuf::from(f),
        _ => usage(),
    };
    if file.extension().map(|e| e != "lume").unwrap_or(true) {
        eprintln!("error: `{}` is not a .lume file", file.display());
        process::exit(2);
    }

    match cmd {
        "emit" => match compile_to_rust(&file) {
            Ok(c) => print!("{}", c.rust),
            Err(e) => {
                eprint!("{}", e);
                process::exit(1);
            }
        },
        "check" => match compile_to_rust(&file) {
            Ok(_) => eprintln!("ok: {}", file.display()),
            Err(e) => {
                eprint!("{}", e);
                process::exit(1);
            }
        },
        "build" => {
            let mut out = None;
            let mut i = 2;
            while i < args.len() {
                if args[i] == "-o" {
                    out = args.get(i + 1).map(PathBuf::from);
                    i += 2;
                } else {
                    usage();
                }
            }
            if let Err(e) = build(&file, out, false) {
                eprint!("{}", e);
                process::exit(1);
            }
        }
        "run" => {
            let prog_args: Vec<&String> = {
                let rest = &args[2..];
                match rest.iter().position(|a| a == "--") {
                    Some(p) => rest[p + 1..].iter().collect(),
                    None => rest.iter().collect(),
                }
            };
            let bin = match build(&file, None, true) {
                Ok(b) => b,
                Err(e) => {
                    eprint!("{}", e);
                    process::exit(1);
                }
            };
            let status = Command::new(&bin)
                .args(prog_args)
                .status()
                .unwrap_or_else(|e| {
                    eprintln!("error: cannot run `{}`: {}", bin.display(), e);
                    process::exit(1);
                });
            process::exit(status.code().unwrap_or(1));
        }
        _ => usage(),
    }
}
